version: "3"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - testvol:/app/data
    expose:
      - 3000

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:3000
    volumes:
      - testvol:/app/data
    expose:
      - 3000

volumes:
  testvol:
